name: flutter_mobile_vision_example
description: Demonstrates how to use the flutter_mobile_vision plugin.

dependencies:
  flutter:
    sdk: flutter
  http: ^0.12.0+4
  cupertino_icons: ^0.1.2
  shared_preferences: ^0.5.4
  share: ^0.6.2+3



dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_mobile_vision:
    path: ../

flutter:

  uses-material-design: true
